spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_user_center
    username: root
    password: 123456

  application:
    name: user-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos


mybatis:
  type-aliases-package: com.lgs.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 8081

pagehelper:
  helper-dialect: mysql

logging:
  level:
    com.lgs.dao: trace
    com.lgs.openfeign.RoleCenterOpenFeign: debug

feign:
  client:
    config:
      role-center:
        logger-level: full

  httpclient:
    enabled: true
